model_params:
  name: 'ConditionalVAE'
  in_channels: 3
  num_classes: 26
  latent_dim: 128

exp_params:
  dataset: malimg
  data_path: "C:\\Users\\ahrn1e19\\malimg\\malimg_paper_dataset_imgs"
  img_size: 64
  batch_size: 144 # Better to have a square number
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: 1
  max_epochs: 150

logging_params:
  save_dir: "logs/"
  name: "ConditionalVAE"
  manual_seed: 1265
