model_params:
  name: 'WAE_MMD'
  in_channels: 3
  latent_dim: 128
  reg_weight: 5000
  kernel_type: 'rbf'

exp_params:
  dataset: malimg
  data_path: "/home/alex/Documents/lectures/project/malimg_paper_dataset_imgs"
  img_size: 32
  batch_size: 144 # Better to have a square number
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: []
  max_nb_epochs: 50
  max_epochs: 50

logging_params:
  save_dir: "logs/"
  name: "WassersteinVAE_RBF"
  manual_seed: 1265




